config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :articles

  get '/about-us' => 'pages#about_us', as: :about_us
  get '/contact-us' => 'pages#contact_us', as: :contact_us
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

    def article_params
      params.required(:article).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about_us
  end

  def contact_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center"><strong>Edit Article</strong></h2>
			<hr>
			<%= render "articles/partial/form" %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h1 class="intro-text text-center">Company
				<strong>Articles Listing</strong>
			</h1>
			<hr>
		</div>
		<% @articles.each do |article| %>

			<div class="col-lg-12 text-center">
				<div class="btn-group" role="group" aria-label="...">
					<%= link_to " Edit", edit_article_path(article), class: "btn btn-default glyphicon glyphicon-edit" %>
					<%= link_to " Delete", article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"},
											class: "btn btn-default glyphicon glyphicon-remove"
					%>
				</div>
				<img class="img-responsive img-border img-full" src="img/slide-1.jpg" alt="">

				<h2><%= link_to article.title, article %>
					<br>
					<small><%= article.created_at.strftime("%B, %d, %Y") %></small>
				</h2>
				<p><%= article.body %></p>
				<%= link_to "Read More", article_path(article), class: "btn btn-default btn-lg" %>
				<hr>
			</div>
		<% end %>

	</div>
</div>

app/views/articles/new.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center"><strong>Add New Article</strong></h2>
			<hr>
			<%= render "articles/partial/form" %>
		</div>
	</div>
</div>

app/views/articles/partial/_form.html.erb
<%= form_for @article, :html => {class: "col-lg-offset-2 col-lg-8", role: "form"} do |f| %>
	<% if @article.errors.any? %>
		<div class="alert alert-danger" role="alert">
			<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
			<%= pluralize(@article.errors.count, 'error') %> preventing to save article
			<% @article.errors.full_messages.each do |msg| %><br/>
				<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
				<span><%= msg %></span>
			<% end %>
		</div>
	<% end %>


	<div class="row">
		<div class="form-group col-lg-12">
			<%= f.label :Title %>
			<%= f.text_field :title, class: "form-control col-lg-12" %>
		</div>
		<div class="clearfix"></div>
		<div class="form-group col-lg-12">
			<%= f.label :Body %>
			<%= f.text_area :body, class: "form-control", rows: "6" %>
		</div>
		<div class="form-group col-lg-12">
			<%= f.submit :submit, class: "btn btn-default" %>
		</div>
	</div>
<% end %>

app/views/articles/show.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center"><strong>Our Articles</strong></h2>
			<hr>
		</div>

		<div class="btn-group col-xs-12" role="group" aria-label="...">
			<%= link_to " Home", root_path, class:"btn btn-default glyphicon glyphicon-home" %>
			<%= link_to " Edit", edit_article_path(@article), class:"btn btn-default glyphicon glyphicon-edit" %>
			<%= link_to " Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"},
									class: "btn btn-default glyphicon glyphicon-remove"
			%>
		</div>
		<div class="col-lg-12 text-center">
			<img class="img-responsive img-border img-full" src="/img/slide-1.jpg" alt="">

			<h2><%= @article.title %>
				<br>
				<small><%= @article.created_at.strftime("%d %b %Y") %></small>
			</h2>
			<p><%= @article.body %>></p>
			<hr>
		</div>

	</div>
</div>

app/views/component/_carousal.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12 text-center">
			<div id="carousel-example-generic" class="carousel slide">
				<!-- Indicators -->
				<ol class="carousel-indicators hidden-xs">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				</ol>

				<!-- Wrapper for slides -->
				<div class="carousel-inner">
					<div class="item active">
						<img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
					</div>
					<div class="item">
						<img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
					</div>
					<div class="item">
						<img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
					</div>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
					<span class="icon-prev"></span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
					<span class="icon-next"></span>
				</a>
			</div>
			<h2 class="brand-before">
				<small>Welcome to</small>
			</h2>
			<h1 class="brand-name">Business Casual</h1>
			<hr class="tagline-divider">
			<h2>
				<small>By
					<strong>Start Bootstrap</strong>
				</small>
			</h2>
		</div>
	</div>
</div>

app/views/component/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
			<a class="navbar-brand" href="index.html">Business Casual</a>
		</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to "HOME", root_path %>
				</li>
				<li>
					<%= link_to "ABOUT US", about_us_path %>
				</li>
				<li>
					<%= link_to "ARTICLES", articles_path %>
				</li>
				<li>
					<%= link_to "CONTACT US", contact_us_path %>
				</li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<p>
					<span>Copyright &copy; Your Website 2016 </span>
					<span>[Developed By: <%= link_to 'SHAHID', 'https://github.com/shahidbscs', :target => '_blank' %>]</span>
				</p>

			</div>
		</div>
	</div>
</footer>

app/views/layouts/_head.html.erb
<div class="brand">Business Casual</div>
<div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Business Casual - Start Bootstrap Theme</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<!-- Fonts -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>
  <%= render "/layouts/head" %>
  <%= render "/component/nav" %>

	<div class="container">
    <%= yield %>
	</div>

  <%= render "/layouts/footer" %>
</body>
</html>

app/views/pages/about_us.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">About
				<strong>business casual</strong>
			</h2>
			<hr>
		</div>
		<div class="col-md-6">
			<img class="img-responsive img-border-left" src="img/slide-2.jpg" alt="">
		</div>
		<div class="col-md-6">
			<p>This is a great place to introduce your company or project and describe what you do.</p>

			<p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes
				nemo minima rerums unsers sadips amets.</p>

			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
				aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
		</div>
		<div class="clearfix"></div>
	</div>
</div>

<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">Our
				<strong>Team</strong>
			</h2>
			<hr>
		</div>
		<div class="col-sm-4 text-center">
			<img class="img-responsive" src="http://placehold.it/750x450" alt="">

			<h3>John Smith
				<small>Job Title</small>
			</h3>
		</div>
		<div class="col-sm-4 text-center">
			<img class="img-responsive" src="http://placehold.it/750x450" alt="">

			<h3>John Smith
				<small>Job Title</small>
			</h3>
		</div>
		<div class="col-sm-4 text-center">
			<img class="img-responsive" src="http://placehold.it/750x450" alt="">

			<h3>John Smith
				<small>Job Title</small>
			</h3>
		</div>
		<div class="clearfix"></div>
	</div>
</div>

app/views/pages/contact_us.html.erb
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">Contact
				<strong>business casual</strong>
			</h2>
			<hr>
		</div>
		<div class="col-md-8">
			<!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
			<iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
		</div>
		<div class="col-md-4">
			<p>Phone:
				<strong>123.456.7890</strong>
			</p>

			<p>Email:
				<strong><a href="mailto:name@example.com">name@example.com</a></strong>
			</p>

			<p>Address:
				<strong>3481 Melrose Place
					<br>Beverly Hills, CA 90210</strong>
			</p>
		</div>
		<div class="clearfix"></div>
	</div>
</div>

<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">Contact
				<strong>form</strong>
			</h2>
			<hr>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, vitae, distinctio, possimus repudiandae
				cupiditate ipsum excepturi dicta neque eaque voluptates tempora veniam esse earum sapiente optio deleniti
				consequuntur eos voluptatem.</p>

			<form role="form">
				<div class="row">
					<div class="form-group col-lg-4">
						<label>Name</label>
						<input type="text" class="form-control">
					</div>
					<div class="form-group col-lg-4">
						<label>Email Address</label>
						<input type="email" class="form-control">
					</div>
					<div class="form-group col-lg-4">
						<label>Phone Number</label>
						<input type="tel" class="form-control">
					</div>
					<div class="clearfix"></div>
					<div class="form-group col-lg-12">
						<label>Message</label>
						<textarea class="form-control" rows="6"></textarea>
					</div>
					<div class="form-group col-lg-12">
						<input type="hidden" name="save" value="contact">
						<button type="submit" class="btn btn-default">Submit</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<%= render "/component/carousal" %>
<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">Build a website
				<strong>worth visiting</strong>
			</h2>
			<hr>
			<img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
			<hr class="visible-xs">
			<p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
			<p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
		</div>
	</div>
</div>

<div class="row">
	<div class="box">
		<div class="col-lg-12">
			<hr>
			<h2 class="intro-text text-center">Beautiful boxes
				<strong>to showcase your content</strong>
			</h2>
			<hr>
			<p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
		</div>
	</div>
</div>